version: "3.8"

services:
 mysql:
  container_name: 'mysql-node'
  image: mysql:5.7
  env_file: ./.env
  restart: always
  ports:
   - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  environment:
   MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   MYSQL_DATABASE: $MYSQL_DATABASE
   MYSQL_USER: $MYSQL_USER
   MYSQL_PASSWORD: $MYSQL_PASSWORD
  networks:
   - microservices
  volumes:
   - "db-config:/etc/mysql"
   - "db-data:/var/lib/mysql"
 phpmyadmin:
  container_name: 'phpmyadmin-node'
  image: phpmyadmin/phpmyadmin
  networks:
   - microservices
  environment:
   PMA_HOST: mysql
   PMA_PORT: 3306
  ports:
   - '8081:80'
  volumes:
   - /sessions
 app:
  container_name: 'node-api'
  build:
    context: .
    dockerfile: ./Dockerfile
  image: node-mysql-app
  depends_on:
    - mysql
  stdin_open: true
  tty: true
  volumes:
   - "./src:/app"
   - "app/node_modules"
  networks:
   - microservices
networks:
 microservices:

volumes:
  db-config:
  db-data:
